[package]
name = "chess_engine"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4"
static-files = "0.2.3"
actix-web-static-files = "4.0.1"

[build-dependencies]
static-files = "0.2.3"